version: '2'

services:
  apache:
    container_name: formation-2-apache
    image: gitlab.prestaconcept.net:7443/docker/apache-php:7.1
    ports:
      - "80:80"
      - "1081:8080"
    volumes:
      - .:/src
    working_dir: /src
    hostname: apache
    links:
      - mysql:mysql
      - maildev:maildev
    extends:
        file: ~/.led/docker-base.yaml
        service: localuser
  mysql:
    container_name: formation-2-mysql
    image: gitlab.prestaconcept.net:7443/docker/mysql:5.6
    ports:
      - "3306:3306"
    hostname: mysql
    volumes:
      - ./.led/storage/mysql:/home/data
      - ./.led/storage/dump:/dump
    extends:
        file: ~/.led/docker-base.yaml
        service: localuser
  maildev:
    container_name: formation-2-maildev
    image: gitlab.prestaconcept.net:7443/docker/maildev
    hostname: maildev
    ports:
      - "1080:80"
