<?php

namespace BlogBundle\Repository;

use BlogBundle\Entity\Post;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get posts form last 2 days
     *
     * @return Post[]
     */
    public function getRecent()
    {
        $dateLimit = new \DateTime();
        $dateLimit->modify('-2 days');

        $queryBuilder = $this->createQueryBuilder('p')
            ->where('p.createdAt > :date')
//            ->setParameter(':date', new \DateTime())
            ->setParameters([
                ':date' => $dateLimit,
            ])
        ;

        $results = $queryBuilder->getQuery()->getResult();

        return $results;
    }
}
